export const REGISTER_COMPANY_SEND = "REGISTER_COMPANY_SEND";
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_FAILED = "REGISTER_COMPANY_FAILED";

export const CHANGE_PRICE_AFTER_DISCOUNT = "CHANGE_PRICE_AFTER_DISCOUNT";

export const SELECT_PROMO = "SELECT_PROMO";

export const CHOOSE_COMPANY_TO_EDIT = "CHOOSE_COMPANY_TO_EDIT";
export const SELECT_COMPANY = "SELECT_COMPANY";

export const DELETE_COMPANY_SEND = "DELETE_COMPANY_SEND";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAILED = "DELETE_COMPANY_FAILED";

export const DELETE_PRODUCT_SEND = "DELETE_PRODUCT_SEND";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const DELETE_PROMO_SEND = "DELETE_PROMO_SEND";
export const DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS";
export const DELETE_PROMO_FAILED = "DELETE_PROMO_FAILED";

export const CHOOSE_PRODUCT_TO_EDIT = "CHOOSE_PRODUCT_TO_EDIT";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const FILTER = "FILTER";

export const EDIT_COMPANY_SEND = "EDIT_COMPANY_SEND";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAILED = "EDIT_COMPANY_FAILED";

export const EDIT_PRODUCT_SEND = "EDIT_PRODUCT_SEND";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";

export const FINISH_PROMO_SEND = "FINISH_PROMO_SEND";
export const FINISH_PROMO_SUCCESS = "FINISH_PROMO_SUCCESS";
export const FINISH_PROMO_FAILED = "FINISH_PROMO_FAILED";

export const START_PROMO_SEND = "START_PROMO_SEND";
export const START_PROMO_SUCCESS = "START_PROMO_SUCCESS";
export const START_PROMO_FAILED = "START_PROMO_FAILED";

export const CHANGE_PROMO_CURRENT_STEP = "CHANGE_PROMO_CURRENT_STEP";

export const CHANGE_PROMO_DISCOUNT = "CHANGE_PROMO_DISCOUNT";
export const CHANGE_PROMO_ABOUT = "CHANGE_PROMO_ABOUT";
export const CHANGE_PROMO_NAME = "CHANGE_PROMO_NAME";
export const CHANGE_PROMO_OBJECTIVE = "CHANGE_PROMO_OBJECTIVE";
export const CHANGE_PROMO_PRODUCT_OBJECT = "CHANGE_PROMO_PRODUCT_OBJECT";
export const CHANGE_PROMO_PRODUCT_ID = "CHANGE_PROMO_PRODUCT_ID";
export const CHANGE_PROMO_REWARD_TYPE = "CHANGE_PROMO_REWARD_TYPE";
export const CHANGE_PROMO_SEPARATE_PRODUCT_ACTION = "CHANGE_PROMO_SEPARATE_PRODUCT_ACTION";
export const CHANGE_PROMO_OFFER_PHRASE = "CHANGE_PROMO_OFFER_PHRASE";
export const CHANGE_PROMO_TERMS = "CHANGE_PROMO_TERMS";
export const CHANGE_PROMO_TYPE = "CHANGE_PROMO_TYPE";
export const CHANGE_PROMO_CONDITION = "CHANGE_PROMO_CONDITION";
export const CHANGE_PROMO_VALUE = "CHANGE_PROMO_VALUE";
export const CHANGE_PROMO_QUANTITY = "CHANGE_PROMO_QUANTITY";
export const CHANGE_PROMO_IS_UNLIMITED_QUANTITY = "CHANGE_PROMO_IS_UNLIMITED_QUANTITY";
export const CHANGE_PROMO_CODES = "CHANGE_PROMO_CODES";
export const CHANGE_PROMO_TIME_DECIDE = "CHANGE_PROMO_TIME_DECIDE";
export const CHANGE_PROMO_GENDER = "CHANGE_PROMO_GENDER";
export const CHANGE_PROMO_AGE = "CHANGE_PROMO_AGE";
export const CHANGE_PROMO_LANGUAGE = "CHANGE_PROMO_LANGUAGE";
export const CHANGE_PROMO_INTEREST = "CHANGE_PROMO_INTEREST";
export const CHANGE_PROMO_SCHEDULE = "CHANGE_PROMO_SCHEDULE";
export const CHANGE_PROMO_PRICING = "CHANGE_PROMO_PRICING";
export const CHANGE_PROMO_START_DATE_TIME = "CHANGE_PROMO_START_DATE_TIME";
export const CHANGE_PROMO_FINISH_DATE_TIME = "CHANGE_PROMO_FINISH_DATE_TIME";
export const CHANGE_PROMO_BUDGET_PERIOD = "CHANGE_PROMO_BUDGET_PERIOD";
export const CHANGE_PROMO_BUDGET_AMOUNT = "CHANGE_PROMO_BUDGET_AMOUNT";
export const CHANGE_PROMO_DATA_LANGUAGE = "CHANGE_PROMO_DATA_LANGUAGE";
export const CHANGE_PROMO_LOCATION = "CHANGE_PROMO_LOCATION";
export const CHANGE_PROMO_CODE_TYPE = "CHANGE_PROMO_CODE_TYPE";
export const CHOOSE_PROMO = "CHOOSE_PROMO";

export const REGISTER_PROMO_SEND = "REGISTER_PROMO_SEND";
export const REGISTER_PROMO_SUCCESS = "REGISTER_PROMO_SUCCESS";
export const REGISTER_PROMO_FAILED = "REGISTER_PROMO_FAILED";

export const EDIT_PROMO_SEND = "EDIT_PROMO_SEND";
export const EDIT_PROMO_SUCCESS = "EDIT_PROMO_SUCCESS";
export const EDIT_PROMO_FAILED = "EDIT_PROMO_FAILED";

export const CHANGE_PROMO_UPLOAD_IMGCODE_SUCCESS = "CHANGE_PROMO_UPLOAD_IMGCODE_SUCCESS";
export const CHANGE_PROMO_UPLOAD_IMGCODE_FAILED = "CHANGE_PROMO_UPLOAD_IMGCODE_FAILED";

export const CHANGE_COMPANY_NAME = "CHANGE_COMPANY_NAME";
export const CHANGE_COMPANY_DESCRIPTION = "CHANGE_COMPANY_DESCRIPTION";
export const CHANGE_COMPANY_EMAIL = "CHANGE_COMPANY_EMAIL";
export const CHANGE_COMPANY_PHONE = "CHANGE_COMPANY_PHONE";
export const CHANGE_COMPANY_CATEGORY = "CHANGE_COMPANY_CATEGORY";
export const CHANGE_COMPANY_SUBCATEGORY = "CHANGE_COMPANY_SUBCATEGORY";
export const CHANGE_COMPANY_WEB_ADDRESS = "CHANGE_COMPANY_WEB_ADDRESS";
export const CHANGE_COMPANY_ADDRESS = "CHANGE_COMPANY_ADDRESS";
export const CHANGE_SHOW_ON_CARD = "CHANGE_SHOW_ON_CARD";
export const CHANGE_COMPANY_LANGUAGE = "CHANGE_COMPANY_LANGUAGE";

export const ADD_SOCIAL_LINK = "ADD_SOCIAL_LINK";
export const CHANGE_SOCIAL_LINK = "CHANGE_SOCIAL_LINK";
export const DELETE_SOCIAL_LINK = "DELETE_SOCIAL_LINK";

export const CHECK_COMPANY_EMAIL_SEND = "CHECK_COMPANY_EMAIL_SEND";
export const CHECK_COMPANY_EMAIL_SUCCESS = "CHECK_COMPANY_EMAIL_SUCCESS";
export const CHECK_COMPANY_EMAIL_FAILED = "CHECK_COMPANY_EMAIL_FAILED";

export const CHECK_COMPANY_WEB_ADDRESS_SEND = "CHECK_COMPANY_WEB_ADDRESS_SEND";
export const CHECK_COMPANY_WEB_ADDRESS_SUCCESS = "CHECK_COMPANY_WEB_ADDRESS_SUCCESS";
export const CHECK_COMPANY_WEB_ADDRESS_FAILED = "CHECK_COMPANY_WEB_ADDRESS_FAILED";

export const CHECK_COMPANY_PHONE_SEND = "CHECK_COMPANY_PHONE_SEND";
export const CHECK_COMPANY_PHONE_SUCCESS = "CHECK_COMPANY_PHONE_SUCCESS";
export const CHECK_COMPANY_PHONE_FAILED = "CHECK_COMPANY_PHONE_FAILED";

export const GET_COMPANY_CATEGORIES_SEND = "GET_COMPANY_CATEGORIES_SEND";
export const GET_COMPANY_CATEGORIES_SUCCESS = "GET_COMPANY_CATEGORIES_SUCCESS";
export const GET_COMPANY_CATEGORIES_FAILED = "GET_COMPANY_CATEGORIES_FAILED";

export const UPLOAD_LOGO_SUCCESS = "UPLOAD_LOGO_SUCCESS";
export const UPLOAD_LOGO_FAILED = "UPLOAD_LOGO_FAILED";

export const CHANGE_PRODUCT_CATEGORY = "CHANGE_PRODUCT_CATEGORY";
export const CHANGE_PRODUCT_NAME = "CHANGE_PRODUCT_NAME";
export const CHANGE_PRODUCT_DESCRIPTION = "CHANGE_PRODUCT_DESCRIPTION";
export const CHANGE_PRODUCT_OBJECT = "CHANGE_PRODUCT_OBJECT";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const CHANGE_PRODUCT_PRICE = "CHANGE_PRODUCT_PRICE";
export const CHANGE_PRODUCT_LINK2PRODUCT = "CHANGE_PRODUCT_LINK2PRODUCT";
export const CHANGE_PRODUCT_EXPDATE = "CHANGE_PRODUCT_EXPDATE";
export const CHANGE_PRODUCT_DATA_LANGUAGE = "CHANGE_PRODUCT_DATA_LANGUAGE";
export const CHANGE_PRODUCT_IS_UNLIMITED = "CHANGE_PRODUCT_IS_UNLIMITED";
export const CHANGE_PRODUCT_IS_UNLIMITED_DATE = "CHANGE_PRODUCT_IS_UNLIMITED_DATE";
export const CHANGE_PRODUCT_IS_ONLINE = "CHANGE_PRODUCT_IS_ONLINE";
export const CHANGE_PRODUCT_IS_OFFLINE = "CHANGE_PRODUCT_IS_OFFLINE";
export const DELETE_PRODUCT_PICTURE = "DELETE_PRODUCT_PICTURE";
export const CHANGE_PICTURES_ORDER = "CHANGE_PICTURES_ORDER";

export const REGISTER_PRODUCT_SEND = "REGISTER_PRODUCT_SEND";
export const REGISTER_PRODUCT_SUCCESS = "REGISTER_PRODUCT_SUCCESS";
export const REGISTER_PRODUCT_FAILED = "REGISTER_PRODUCT_FAILED";

export const CHANGE_PRODUCT_UPLOAD_IMAGE_LOADING = "CHANGE_PRODUCT_UPLOAD_IMAGE_LOADING";
export const CHANGE_PRODUCT_UPLOAD_IMAGE_SUCCESS = "CHANGE_PRODUCT_UPLOAD_IMAGE_SUCCESS";
export const CHANGE_PRODUCT_UPLOAD_IMAGE_FAILED = "CHANGE_PRODUCT_UPLOAD_IMAGE_FAILED";
export const CHANGE_PRODUCT_UPLOAD_IMAGE_FAILED_WRONG_EXTENSION = "CHANGE_PRODUCT_UPLOAD_IMAGE_FAILED_WRONG_EXTENSION";
export const CHANGE_PRODUCT_UPLOAD_IMAGE_FAILED_SIZE_EXCEEDED = "CHANGE_PRODUCT_UPLOAD_IMAGE_FAILED_SIZE_EXCEEDED";

export const CHANGE_NEW_PASSWORD = "CHANGE_NEW_PASSWORD";
export const CHANGE_NEW_VERIFY = "CHANGE_NEW_VERIFY";

export const APPLY_NEW_PASSWORD_SEND = "APPLY_NEW_PASSWORD_SEND";
export const APPLY_NEW_PASSWORD_SUCCESS = "APPLY_NEW_PASSWORD_SUCCESS";
export const APPLY_NEW_PASSWORD_FAILED = "APPLY_NEW_PASSWORD_FAILED";

export const LOAD_USER_COMPANIES_SEND = "LOAD_USER_COMPANIES_SEND";
export const LOAD_USER_COMPANIES_SUCCESS = "LOAD_USER_COMPANIES_SUCCESS";
export const LOAD_USER_COMPANIES_FAILED = "LOAD_USER_COMPANIES_FAILED";

export const NEW_PRODUCT = "NEW_PRODUCT";
export const NEW_COMPANY = "NEW_COMPANY";
export const NEW_PROMO = "NEW_PROMO";

export const CHOOSE_COMPANY = "CHOOSE_COMPANY";
export const CHOOSE_COOKIED_COMPANY = "CHOOSE_COOKIED_COMPANY";
export const CHOOSE_PRODUCT = "CHOOSE_PRODUCT";
export const CHOOSE_PROMO_TO_VIEW = "CHOOSE_PROMO_TO_VIEW";

export const LOAD_COMPANY_PRODUCTS_SEND = "LOAD_COMPANY_PRODUCTS_SEND";
export const LOAD_COMPANY_PRODUCTS_SUCCESS = "LOAD_COMPANY_PRODUCTS_SUCCESS";
export const LOAD_COMPANY_PRODUCTS_FAILED = "LOAD_COMPANY_PRODUCTS_FAILED";

export const LOAD_COMPANY_PROMOS_SEND = "LOAD_COMPANY_PROMOS_SEND";
export const LOAD_COMPANY_PROMOS_SUCCESS = "LOAD_COMPANY_PROMOS_SUCCESS";
export const LOAD_COMPANY_PROMOS_FAILED = "LOAD_COMPANY_PROMOS_FAILED";

export const LOAD_COMPANY_PROMO_STATISTICS_SEND = "LOAD_COMPANY_PROMO_STATISTICS_SEND";
export const LOAD_COMPANY_PROMO_STATISTICS_SUCCESS = "LOAD_COMPANY_PROMO_STATISTICS_SUCCESS";
export const LOAD_COMPANY_PROMO_STATISTICS_FAILED = "LOAD_COMPANY_PROMO_STATISTICS_FAILED";

export const UPDATE_STATISTICS = "UPDATE_STATISTICS";
