export enum ServerErrorCode {
    NOT_FOUND = "NOT_FOUND",
    BAD_REQUEST = "BAD_REQUEST",
    AUTH_ERROR = "AUTH_ERROR",
    FACEBOOK_ID_NOT_FOUND = "FACEBOOK_ID_NOT_FOUND",
    FACEBOOK_ID_NOT_UNIQUE = "FACEBOOK_ID_NOT_UNIQUE",
    EMAIL_NOT_UNIQUE = "EMAIL_NOT_UNIQUE",
    EMAIL_NOT_VALID = "EMAIL_NOT_VALID",
    PHONE_NOT_UNIQUE = "PHONE_NOT_UNIQUE",
    WEB_ADDRESS_NOT_UNIQUE = "WEB_ADDRESS_NOT_UNIQUE"
}
