export const CHANGE_LOGIN = "CHANGE_LOGIN";
export const CHANGE_CREDENTIAL = "CHANGE_CREDENTIAL";
export const CHANGE_KEEP_LOGGED = "CHANGE_KEEP_LOGGED";

export const SWITCH_TO_SIGNIN_FORM = "SWITCH_TO_SIGNIN_FORM";
export const SWITCH_TO_RECOVER_FORM = "SWITCH_TO_RECOVER_FORM";
export const SWITCH_TO_SIGNUP_FORM = "SWITCH_TO_SIGNUP_FORM";

export const LOGIN_SEND = "LOGIN_SEND";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGIN_VIA_FACEBOOK_SEND = "LOGIN_VIA_FACEBOOK_SEND";
export const LOGIN_VIA_FACEBOOK_SUCCESS = "LOGIN_VIA_FACEBOOK_SUCCESS";
export const LOGIN_VIA_FACEBOOK_FAILED = "LOGIN_VIA_FACEBOOK_FAILED";

export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_FAMILY_NAME = "CHANGE_FAMILY_NAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_VERIFY = "CHANGE_VERIFY";
export const CHANGE_IS_ON_DISPATCH = "CHANGE_IS_ON_DISPATCH";

export const CHECK_EMAIL_SEND = "CHECK_EMAIL_SEND";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAILED = "CHECK_EMAIL_FAILED";

export const REGISTER_USER_SEND = "REGISTER_USER_SEND";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const REGISTER_USER_VIA_FACEBOOK_SEND = "REGISTER_USER_VIA_FACEBOOK_SEND";
export const REGISTER_USER_VIA_FACEBOOK_SUCCESS = "REGISTER_USER_VIA_FACEBOOK_SUCCESS";
export const REGISTER_USER_VIA_FACEBOOK_FAILED = "REGISTER_USER_VIA_FACEBOOK_FAILED";

export const CHANGE_RECOVER_EMAIL = "CHANGE_RECOVER_EMAIL";

export const RECOVER_PASS_SEND = "RECOVER_PASS_SEND";
export const RECOVER_PASS_SUCCESS = "RECOVER_PASS_SUCCESS";
export const RECOVER_PASS_FAILED = "RECOVER_PASS_FAILED";
