export const LOGOUT_SEND = "LOGOUT_SEND";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const LOAD_USER_INFO_SEND = "LOAD_USER_INFO_SEND";
export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS";
export const LOAD_USER_INFO_FAILED = "LOAD_USER_INFO_FAILED";
